### ISSUE TITLE
Few typos in documentation

### ISSUE THREAD

**Issue by dshum** [LonelyVikingMichael/litestar-users#70]
A few typos that may confuse the user (at least they confused me):

https://lonelyvikingmichael.github.io/litestar-users/usage/0-configuration/
`LitestarUsers -> LitestarUsersPlugin`
```
litestar_users = LitestarUsers(
    config=LitestarUsersConfig(
```

https://lonelyvikingmichael.github.io/litestar-users/usage/6-command-line-interface/
`--is_verified -> --is-verified, --is_active -> --is-active`
```
--is_verified
Set the user as being verified.
--is_active
Set the user as active.
```

**Comment by edimedia** [comment]
Yes, docs need to be updated
